name: chat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  email_validator: ^2.0.1
  image_picker: 0.8.5+3
  intl: ^0.17.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
      - family: CustomIcons
        fonts:
          - asset: fonts/CustomIcons.ttf
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
